runtime: nodejs18

env_variables:
  FIREBASE_API_KEY: "AIzaSyAH5PD5HPuZCOeiYwjUPD9VMAEQicSmG8Y"
  FIREBASE_AUTH_DOMAIN: "litswap-project.firebaseapp.com"
  FIREBASE_PROJECT_ID: "litswap-project"
  FIREBASE_STORAGE_BUCKET: "litswap-project.appspot.com"
  FIREBASE_MESSAGING_SENDER_ID: "357232983996"
  FIREBASE_APP_ID: "1:357232983996:web:2e6ad86aa459e1fde535b9"
  FIREBASE_MEASUREMENT_ID: "G-DDPRTXB3H2"
